"""Setup script to convert Colab notebooks to run locally.

This script:
  1. Creates backups of the original notebooks.
  2. Removes or replaces Google Drive mount cells.
  3. Replaces hard-coded Colab paths (dataset + task files) with local paths.
  4. Prepends a "Local Setup" cell at the top that loads .env / src helpers.

Usage:
  python setup_notebooks.py            # convert all step notebooks
  python setup_notebooks.py --dry-run  # show changes without writing files
"""

import json
import shutil
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from src.config import DATASET_DIR, STEPCASE

NOTEBOOKS = {
    1: PROJECT_ROOT / "step1" / "Data_Mining_Task1.ipynb",
    2: PROJECT_ROOT / "step2" / "Data_Mining_Task2.ipynb",
    3: PROJECT_ROOT / "step3" / "Data_Mining_Task3.ipynb",
    4: PROJECT_ROOT / "step4" / "Data_Mining_Task4.ipynb",
    5: PROJECT_ROOT / "step5" / "Data_Mining_Task_5ipynb.ipynb",
}

COLAB_DRIVE_MARKERS = (
    "from google.colab import drive",
    "drive.mount(",
    "Mount Google Drive",
)

COLAB_DATASET_PREFIX = "/content/drive/MyDrive/Data Mining Project UIUC/dataset/"

COLAB_TASK_MAP = {
    1: "/content/drive/MyDrive/Data Mining Project UIUC/task1/",
    2: "/content/drive/MyDrive/Data Mining Project UIUC/task2/",
    3: "/content/drive/MyDrive/Data Mining Project UIUC/task3/",
    4: "/content/drive/MyDrive/Data Mining Project UIUC/task4/",
    5: "/content/drive/MyDrive/Data Mining Project UIUC/task5/",
}

LOCAL_SETUP_CELL = {
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# ===== Local Setup (auto-generated by setup_notebooks.py) =====\n",
        "# Run this cell FIRST to configure paths and check dataset files.\n",
        "import os, sys\n",
        "from pathlib import Path\n",
        "\n",
        "# Allow notebooks to import the `src` package from project root\n",
        "PROJECT_ROOT = Path.cwd().resolve()\n",
        "while not (PROJECT_ROOT / 'src').exists() and PROJECT_ROOT.parent != PROJECT_ROOT:\n",
        "    PROJECT_ROOT = PROJECT_ROOT.parent\n",
        "if str(PROJECT_ROOT) not in sys.path:\n",
        "    sys.path.insert(0, str(PROJECT_ROOT))\n",
        "\n",
        "try:\n",
        "    from dotenv import load_dotenv\n",
        "    load_dotenv(PROJECT_ROOT / '.env')\n",
        "    print('[OK] Loaded .env')\n",
        "except ImportError:\n",
        "    print('[INFO] python-dotenv not installed; .env ignored (pip install python-dotenv)')\n",
        "\n",
        "from src.config import DATASET_DIR, STEPCASE, check_dataset, dataset_path, step_dir\n",
        "\n",
        "# Shortcuts commonly used in the notebooks (same names for compatibility)\n",
        "business_file_path = str(dataset_path('business'))\n",
        "review_file_path   = str(dataset_path('review'))\n",
        "try:\n",
        "    tip_file_path = str(dataset_path('tip'))\n",
        "except Exception:\n",
        "    tip_file_path = ''\n",
        "\n",
        "# Current step directory (auto-detected from notebook location)\n",
        "HERE = Path(os.getcwd()).resolve()\n",
        "print(f'[INFO] Project root : {PROJECT_ROOT}')\n",
        "print(f'[INFO] Dataset dir  : {DATASET_DIR}')\n",
        "check_dataset();\n",
    ],
}


def source_matches(cell, markers):
    text = "".join(cell.get("source", [])).lower()
    return any(m.lower() in text for m in markers)


def replace_paths(text: str, step_num: int) -> str:
    text = text.replace(COLAB_DATASET_PREFIX, str(DATASET_DIR) + "/")
    colab_task_prefix = COLAB_TASK_MAP.get(step_num, "")
    if colab_task_prefix:
        step_folder = STEPCASE[step_num]
        text = text.replace(colab_task_prefix, str(step_folder) + "/")
    return text


def patch_notebook(nb_path: Path, step_num: int, dry_run: bool = False):
    with open(nb_path, "r", encoding="utf-8") as f:
        nb = json.load(f)

    original_cells = nb["cells"]
    new_cells = []
    changes = {"drive_cells_removed": 0, "paths_replaced": 0}

    for cell in original_cells:
        if cell.get("cell_type") == "code" and source_matches(cell, COLAB_DRIVE_MARKERS):
            if not any("LOCAL SETUP" in "".join(cell.get("source", [])).upper()
                       for c in new_cells if c.get("cell_type") == "code"):
                new_cells.append(json.loads(json.dumps(LOCAL_SETUP_CELL)))
            changes["drive_cells_removed"] += 1
            continue

        for k in ("source",):
            if isinstance(cell.get(k), list):
                orig = "".join(cell[k])
                new_text = replace_paths(orig, step_num)
                if new_text != orig:
                    changes["paths_replaced"] += 1
                    cell[k] = [new_text[i:i + 1] for i in range(len(new_text))]
                    cell[k] = list(new_text)
                    cell[k] = [new_text] if new_text else [""]
                    cell[k] = _lines_from_string(new_text)

        if cell.get("cell_type") == "markdown":
            cell["source"] = _lines_from_string(replace_paths("".join(cell.get("source", [])), step_num))

        new_cells.append(cell)

    if not any("LOCAL SETUP" in "".join(c.get("source", [])).upper()
               for c in new_cells if c.get("cell_type") == "code"):
        new_cells.insert(0, json.loads(json.dumps(LOCAL_SETUP_CELL)))

    nb["cells"] = new_cells

    backup = nb_path.with_suffix(nb_path.suffix + ".original")
    if not dry_run and not backup.exists():
        shutil.copy2(nb_path, backup)

    if not dry_run:
        with open(nb_path, "w", encoding="utf-8") as f:
            json.dump(nb, f, indent=1, ensure_ascii=False)

    print(f"  [{'DRY' if dry_run else 'OK '}] Step {step_num} -> {nb_path.name}  "
          f"(removed drive={changes['drive_cells_removed']}, path-edits={changes['paths_replaced']})")
    return nb


def _lines_from_string(s: str):
    if not s:
        return [""]
    lines = s.splitlines(keepends=True)
    return lines


def main():
    dry_run = "--dry-run" in sys.argv
    steps = [int(a.split("=")[1]) for a in sys.argv[1:] if a.startswith("--step=")]
    targets = steps if steps else list(NOTEBOOKS.keys())

    print(f"Patching notebooks (dry_run={dry_run}, steps={targets})")

    for s in targets:
        if not NOTEBOOKS[s].exists():
            print(f"  [SKIP] Step {s}: notebook not found at {NOTEBOOKS[s]}")
            continue
        patch_notebook(NOTEBOOKS[s], s, dry_run=dry_run)

    print("\nDone. If the .env is not set, place the Yelp dataset JSON files in:")
    print(f"  {DATASET_DIR}")
    print("Or set YELP_DATASET_DIR in a .env file at the project root.")


if __name__ == "__main__":
    main()
